### ISSUE TITLE
Add Ahorn tooltips

### ISSUE THREAD

**Issue by PIXELATOR37** [catapillie/VortexHelper#27]
So far this has been done for: custom switch gates, floor boosters, color switches, purple/lavender boosters, pufferfish bowls. Everything else needs tooltips written still

**Comment by catapillie** [comment]
Missing tooltips were written during the addition of Lönn plugins.
They were copied into the Ahorn lang file in https://github.com/catapillie/VortexHelper/commit/b5358613c3509b59f7f8b4fca694d1e73d647b9e.
